CREATE USER 'bizuser'@'%' IDENTIFIED BY 'secretpassword';
GRANT ALL PRIVILEGES ON JFC.* to 'bizuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE JFC;

USE JFC;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
  ID INT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  TELEGRAM_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
  ID INT AUTO_INCREMENT NOT NULL,
  DATE BIGINT NOT NULL,
  REMARKS  VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS PAYMENTDUE;
CREATE TABLE PAYMENT_DUE (
  ID INT AUTO_INCREMENT NOT NULL,
  PAYER INT NOT NULL,
  PAYMENT_DUE BIGINT,
  PAYABLE_AMOUNT FLOAT(2) NOT NULL,
  PAID BOOL NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (PAYER) REFERENCES PERSON(ID)
);

INSERT INTO PERSON (NAME, TELEGRAM_ID) VALUES (
  "Jonathan", "@jonny"
);