CREATE USER 'bizuser'@'%' IDENTIFIED BY 'secretpassword';
GRANT ALL PRIVILEGES ON JFC.* to 'bizuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE JFC;

USE JFC;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
  ID INT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  TELEGRAM_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
  ID INT AUTO_INCREMENT NOT NULL,
  DATE BIGINT NOT NULL,
  REMARKS  VARCHAR(255) NOT NULL,
  TOTAL_AMOUNT FLOAT(2) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS PAYMENT_DUE;
CREATE TABLE PAYMENT_DUE (
  ID INT AUTO_INCREMENT NOT NULL,
  PAYER_ID INT NOT NULL,
  PAYMENT_ID INT NOT NULL,
  PAYMENT_DUE_DATE BIGINT,
  PAYABLE_AMOUNT FLOAT(2) NOT NULL,
  PAID BOOL NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (PAYER) REFERENCES PERSON(ID),
  FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(ID)
);

INSERT INTO PERSON (NAME, TELEGRAM_ID) VALUES (
  "Jonathan", "@jonny"
);

INSERT INTO PAYMENT (DATE, REMARKS, TOTAL_AMOUNT) VALUES (
  1703041312, "Payment for XX", 288.32
);

INSERT INTO PAYMENT_DUE (PAYER, PAYMENT_DUE_DATE, PAYABLE_AMOUNT, PAID, PAYMENT_ID) VALUES (
  (SELECT ID FROM PERSON WHERE NAME='Jonathan'), 1703991712, 90.28, FALSE, (SELECT ID FROM PAYMENT WHERE ID=1)
);